---
# declare the session options for express
SESSION_EXPRESS:
  secret: 'keyboardCatzilla'
  resave: false
  saveUninitialized: true
  cookie: 
    maxAge: 60000

# declare the session options for redis
# "secret" will be used to create the session ID hash (the cookie id and the redis key value)
# "name" will show up as your cookie name in the browser
# "cookie" is provided by default; you can add it to add additional personalized options
# The "store" ttl is the expiration time for each Redis session ID, in seconds
SESSION_REDIS:
  secret: 'ThisIsHowYouUseRedisSessionStorage'
  name: '_redisPractice'
  resave: false
  saveUninitialized: true
  cookie: 
    secure: false # Note that the cookie-parser module is no longer needed
...